#!/bin/bash
SYSROOT=/data/misc/rpc

arm-linux-gnueabihf-g++ \
-DLINUX=1 -DDEBUG=1 -D_DEBUG=1 \
-DJUCER_LINUX_MAKE_6D53C8B4=1 -DJUCE_APP_VERSION=1.0.0 \
-DJUCE_APP_VERSION_HEX=0x10000 -pthread \
-I../../JuceLibraryCode -I../../JuceLibraryCode/modules \
-I$SYSROOT/usr/include \
-marm -march=armv6 -g -ggdb -O0  -std=c++14 \
-DJucePlugin_Build_VST=0 -DJucePlugin_Build_VST3=0 \
-DJucePlugin_Build_AU=0 -DJucePlugin_Build_AUv3=0 \
-DJucePlugin_Build_RTAS=0 -DJucePlugin_Build_AAX=0 \
-DJucePlugin_Build_Standalone=0 -DJucePlugin_Build_Unity=0 \
-o "MainComponent.o" -c "../../Source/MainComponent.cpp"
